SQLALCHEMY_DATABASE_URI='sqlite:///tmp.db'
SQLALCHEMY_TRACK_MODIFICATIONS=True
SQLALCHEMY_ECHO=False
MAX_CONTENT_LENGTH=4*1024*1024
IMAGE_UPLOAD_DIRECTORY='images/'

LOG_ACCESS='access.log'
LOG_ERRORS='errors.log'
